AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ElasticIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

Outputs:
  EIPOutput1:
    Value: !Ref ElasticIP2
    Export:
      Name: "EIP2"
